services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market-db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pipeline:
    build:
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=postgresql+psycopg2://admin:admin@db:5432/market-db
      - STOCKDATA_API_TOKEN=${STOCKDATA_API_TOKEN}
    depends_on:
      - db

volumes:
  pgdata: